[project]
name = "clicrm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "tabulate>=0.9.0",
    "typer-slim>=0.15.2",
]

[tool.setuptools]
py-modules = ["clicrm"]
